#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
# Requirements:
#       Install nginx on your web-01
#       server
#       Nginx should be listening on port 80
#       When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
#       As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
#       You can’t use systemctl for restarting nginx


sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start
