#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  http_front
        bind *:80
        mode http
        default_backend http_back
backend http_back
        balance roundrobin
        server 427881-web-01 54.237.218.228:80 check
        server 427881-web-02 34.203.75.52:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# restart
sudo service haproxy restart
