#!/usr/bin/env bash
# A  Bash script that displays a list of currently runnit processes.
# Shows all users, including those which might not have a TTY
# Displays in a user-oriented format
# Shows process hierarchy

ps -auxf
