#!/usr/bin/env bash
# A Bash script that displays:
# 	To infinity and beyond indefinitely
#	With a sleep 2 in between each iteration
#	I am invincible!!! when receiving a SIGTERM signal

MSG () {
	echo -e "I am invincible!!!" 
}

trap "MSG" SIGTERM

while true; do
	echo -e "To infinity and beyond"
	sleep 2
done
