#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
# Script should only displays:
#	username
#	user id
#	Home directory path for the user 

file="/etc/passwd"

while read -r line; do
	echo -e "${line}" | cut -d ":" -f1,3,6
done < $file
