#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes
# Display hours from 0 to 12
# Display minutes from 1 to 59

i=0
while [ "$i" -le 12 ]; do
	echo -e "Hour: ${i}"
	min=1
	while [ "$min" -le 59 ]; do
		echo -e "${min}"
		min="$((min+1))"
	done
	i="$((i+1))"
done
