#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
